#!/bin/bash
# Script to do the desired final config/setup steps on a Ubuntu (18.04) system
#
# Based on the previous cloud-config.txt file (runcmd and write_files sections) from the former "vm-ubuntuserver-1804" template (...)

echo
echo "BELEROFONTECH - STARTING CUSTOM 'FINAL CONFIG AND ENVIRONMENT' INIT!"

# Optional: more debug info (show executed commands)
# set -x

# Define default variable values if missing

# MAINUSER is the preferred/expected var to get the desired value from outside; SUDO_USER can be used also,
# in case MAINUSER is not defined. If none of the two are defined/available, set a default value: "belero"
[[ -z "$MAINUSER" ]] && [[ ! -z "$SUDO_USER" ]] && [[ "root" != "$SUDO_USER" ]] && MAINUSER="$SUDO_USER"
[[ -z "$MAINUSER" ]] && MAINUSER="belero"
echo "Value for MAINUSER variable: $MAINUSER"

# Check for root permissions (user id = 0)
if [[ $( id -u ) != 0 ]]
then
    echo "This script must be run with root privileges"
    exit 1
fi

# Avoid apt-get commands to ask config/setup questions interactively (Debian/Ubuntu)
export DEBIAN_FRONTEND=noninteractive

sh -xc 'date ; env ; whoami ; pwd'

# Set vim as default editor
update-alternatives --set editor /usr/bin/vim.basic

# Customized user config (default editor). Otherwise, this is asked the first time it is needed
# We do this both for future users (/etc/skel) and the current "main" one...
cat > /etc/skel/.selected_editor << EOF
# Generated by /usr/bin/select-editor; Belerofontech cloud-init generated
SELECTED_EDITOR="/usr/bin/vim.basic"
EOF
chmod 0664 /etc/skel/.selected_editor
cp -a /etc/skel/.selected_editor /home/$MAINUSER
chown $MAINUSER:$MAINUSER /home/$MAINUSER/.selected_editor

# Customized (system-wide) environment variables and commands at each login
# NOTE: the last line contains a $ that we want "as is", therefore it is escaped: \$
cat > /etc/profile.d/Z99-zz-belero.sh << EOF
# Belerofontech cloud-init generated file
#
# Belerofontech: set vim as default editor
export EDITOR=vim
export VISUAL=vim
# Belerofontech matplotlib configuration for headless server
export MPLBACKEND=agg
# Belerofontech hack to add some debug info to the user history (access time, IP address, etc.) at login
history -r && history -s echo @@@ LOGIN @@@ \$(last -n1 --time iso | head -n1)
EOF
chmod 0755 /etc/profile.d/Z99-zz-belero.sh

# Customized system info shown at each login
# Originally, there was a similar behaviour with 50-landscape-sysinfo (symlink to /usr/share/landscape/landscape-sysinfo.wrapper ...)
cat > /etc/update-motd.d/50-belero-sysinfo << EOF
#!/bin/sh
# Belerofontech cloud-init generated file
#
# Customized system info shown at each login (MOTD), instead of the default one
echo
## TO-DO: Optional: more changes in the info that is shown by neofetch (...)
## Config in: /etc/neofetch/... or in /home/xxx/.config/neofetch/config.conf
which neofetch 2>/dev/null >/dev/null && neofetch --config none --shell_path on --cpu_display infobar --memory_display infobar --battery_display infobar --disk_display infobar
echo
echo BELEROFONTECH AZURE VIRTUAL MACHINE. Cloud-init instance info:
cloud-init query ds.meta_data | grep -e '"name"\|"resourceGroupName"\|"subscriptionId"\|"tags"\|pAddress": "' | xargs echo
## TO-DO: get also the DNS name. Needs Azure CLI installed, and getting VM info (group, etc.) previously (...)
## https://docs.microsoft.com/en-us/cli/azure/network/public-ip?view=azure-cli-latest#az_network_public_ip_show
## az network public-ip show -g RESOURCEGROUP... -n vm-nic-name... -o json --query "{fqdn: dnsSettings.fqdn, publicIpAddress: ipAddress}" | tr -d '{}' ) | xargs echo
echo
w
# Show only info about zombie processes, inspired from the original landscape-sysinfo output
# which landscape-sysinfo 2>/dev/null >/dev/null && landscape-sysinfo --sysinfo-plugins=Processes 2>/dev/null
ps -elf | grep "^[0-9]\+ Z " | grep " Z " && ps -elf | head -n1 && echo "Zombie process(es) detected!" | grep "Zombie.*"
# NOTE: this script must finish successfully for the MOTD info to be correctly updated and shown!
exit 0
EOF
chmod 0755 /etc/update-motd.d/50-belero-sysinfo

# Small "notice" (informative) file at the usual directory for mounts
mkdir -p /media/belero
cat > /media/belero/README.txt << EOF
This directory is used for shared data and utilities
EOF
chmod 0644 /media/belero/README.txt


# NOTE: insert other/future steps here, before the final "blocks"...
# (...)


# Final "blocks"

# Apt cleanup
apt-get -y autoremove
apt-get clean

# Update the file search DB for the "locate" system tool
updatedb

# Link to the cloud-init logs, to facilitate checking them after VM creation (also allows to indicate that it has almost ended)
ln -s /var/log/cloud-init-output.log /home/$MAINUSER

# Optional: poweroff or reboot system after the config has finished.
# echo "BELEROFONTECH - WILL REBOOT NOW (IN 2 MINUTES)!"
# shutdown +2 -r "Reboot after VM init has finished"

echo
echo "BELEROFONTECH - FINISHED CUSTOM 'FINAL CONFIG AND ENVIRONMENT' INIT!"

# # Optional: use this to force output to be shown, when run remotely on Azure with "run-custom-script.sh" (making the script exit status != 0 means that it didn't finish successfully)
# echo "FINISHED. Now will end script execution with error status 101..." 1>&2
# exit 101
